name: dpdp
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3
  - git
  - joblib
  - jupyter
  - nose
  - matplotlib
  - ipython
  - numpy
  - pip
  - scikit-learn
  - scipy
  - tqdm
  - pytorch
  - cudatoolkit=10.2
